#!/bin/sh

_ctrlc() {
    echo "Caught Ctrl^C signal"
    kill -TERM $child 2>/dev/null
    wait "$child"
    exit $?
}

_term() {
    echo "Caught SIGTERM signal"
    kill -TERM $child 2>/dev/null
    wait "$child"
    exit $?
}

trap _term SIGTERM
trap _ctrlc INT

echo java "$@"
java "$@" &
child=$!

wait "$child"
exit $?
